# The Site Configuration

lang: vi-VN
timezone: Asia/Ho_Chi_Minh

title: Kevinnkv
tagline: HTB Writeups & SOC Notes

description: >-
  My cybersecurity journey.

url: "https://Kevinnkv.github.io"
baseurl: ""

github:
  username: Kevinnkv

social:
  name: Kevinnkv
  email: your-email@example.com
  links:
    - https://github.com/Kevinnkv

theme_mode: dark

avatar: "/assets/img/avatar.png"

toc: true

paginate: 10